using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PegasusBackend.Models
{
    public class IdempotencyRecord
    {
        // The unique key generated by the frontend (GUID/UUID)
        [Key]
        [MaxLength(100)]
        public string IdempotencyKey { get; set; } = null!;

        // The booking created with this key
        [Required]
        public int BookingId { get; set; }

        // When this key was first used
        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // Response data that was returned (serialized JSON)
        // Allows returning the exact same response on retry
        [Required]
        public string ResponseData { get; set; } = null!;

        // HTTP status code that was returned (200, 400, etc.)
        [Required]
        public int StatusCode { get; set; }

        // When this record should be cleaned up
        // Default: 24 hours from creation
        [Required]
        public DateTime ExpiresAt { get; set; }

        // Navigation property to the related booking
        [ForeignKey(nameof(BookingId))]
        public virtual Bookings Booking { get; set; } = null!;
    }
}
